import { StoryBook } from './types';

export const PRESET_STORIES: StoryBook[] = [
  {
    id: 'kancil-robot-hutan',
    title: 'Si Kancil dan Robot Pembersih Hutan',
    tagline: 'Kecerdikan kuno bertemu kebaikan teknologi demi kelestarian rimba.',
    moralLesson: 'Kemajuan teknologi paling bernilai ketika digunakan untuk merawat alam dan bekerja sama dengan sesama makhluk.',
    readingTimeMinutes: 5,
    targetAgeGroup: '5 - 8 Tahun',
    genre: 'Fabel Fiksi Ilmiah Anak',
    artStyle: 'Cat Air Lembut & Desain Modern',
    characters: [
      { name: 'Kancil', role: 'Kancil Cerdik', traits: 'Pintar, ramah, dan peduli lingkungan', emoji: '🦌' },
      { name: 'Boti', role: 'Robot Pembersih', traits: 'Roda bulat, mata lampu biru yang ramah, gemar memungut sampah', emoji: '🤖' },
      { name: 'Burung Kutilang', role: 'Pemandu Udara', traits: 'Bernyanyi merdu dan pandai mengamati dari dahan', emoji: '🐦' },
    ],
    cover: {
      visualDescription: 'Kancil tersenyum di samping robot bulat bersahabat di tengah hutan zamrud yang berkilauan embun pagi.',
      sceneSetting: 'enchanted-forest',
      colorPalette: 'emerald-gold',
    },
    createdAt: '2026-10-01',
    pages: [
      {
        pageNumber: 1,
        sceneTitle: 'Suara Gemerincing Aneh di Balik Semak',
        narrativeText: 'Di Hutan Rimba Harapan yang rindang, matahari pagi baru saja menyapa daun-daun basah. Si Kancil yang sedang mencari buah ara manis tiba-tiba mendengar bunyi aneh: "Klink... klong... wuuung!" Dari balik semak ilalang, meluncur sebuah makhluk bulat berkilauan dengan roda kecil dan antena berkedip.',
        englishTranslation: 'In the lush Green Hope Forest, the morning sun had just greeted the wet leaves. Mousedeer heard a curious sound from the bushes, where a round shiny creature with little wheels and a blinking antenna rolled out.',
        dialogue: '"Halo sahabat kecil! Namaku Boti, robot pembersih tercanggih!" sapa si robot dengan bunyi ceria.',
        interactiveQuestion: 'Apa yang akan kamu katakan jika bertemu robot ramah di dalam hutan?',
        activityPrompt: 'Tirukan bunyi roda si robot: "Nguuung... klink!"',
        sceneSetting: 'enchanted-forest',
        colorPalette: 'emerald-gold',
        illustrationPrompt: 'Kancil terkejut gembira menatap robot kecil bulat berkilau di antara semak bunga hutan',
      },
      {
        pageNumber: 2,
        sceneTitle: 'Tumpukan Sampah di Tepi Danau Jernih',
        narrativeText: 'Boti bercerita bahwa ia tersesat dari tepi kota manusia saat berusaha mengumpulkan botol-botol plastik yang hanyut di sungai. Di tepi Danau Jernih, banyak ranting dan kantong plastik yang menyumbat aliran air, membuat ikan-ikan kecil tidak bisa berenang leluasa. Hati Kancil tergerak untuk membantu sahabat barunya.',
        englishTranslation: 'Boti explained he wandered from the city while collecting floating plastic bottles in the river. At Clear Lake, branches and trash blocked the water stream. Mousedeer felt moved to help his new friend.',
        dialogue: '"Jangan cemas, Boti! Hutan ini rumahku. Kita bersihkan bersama-sama!" seru Kancil dengan semangat.',
        interactiveQuestion: 'Mengapa menjaga kebersihan sungai dan danau sangat penting bagi hewan-hewan?',
        activityPrompt: 'Coba sebutkan 2 barang di sekitarmu yang bisa didaur ulang!',
        sceneSetting: 'mountain-river',
        colorPalette: 'azure-cyan',
        illustrationPrompt: 'Kancil dan robot Boti di tepi danau berair biru toska, memandangi aliran sungai yang tersumbat ranting',
      },
      {
        pageNumber: 3,
        sceneTitle: 'Kecerdikan Kancil dan Tangan Besi Boti',
        narrativeText: 'Kancil memanjat batu tinggi untuk memetakan sampah yang tersangkut. Dengan siulan khasnya, ia memanggil kawan-kawan kutilang untuk mengangkat dedaunan kering. Sementara itu, Boti mengulurkan lengan magnetisnya dengan lincah, memilah botol dan kaleng ke dalam kantong ramah lingkungannya tanpa merusak satu bunga pun.',
        englishTranslation: 'Mousedeer climbed a tall stone to scout the blocked spots. Calling the birds to lift dry twigs, Boti stretched out his gentle magnetic arms, gathering bottles without hurting a single blossom.',
        dialogue: '"Tiiit-tut! Sampah logam terdeteksi, siap didaur ulang menjadi pot tanaman!" lapor Boti gembira.',
        interactiveQuestion: 'Bagaimana perasaanmu ketika bekerja sama membersihkan ruangan bersama teman?',
        activityPrompt: 'Goyangkan tanganmu seperti lengan robot magnet Boti: Zuuup!',
        sceneSetting: 'sunny-meadow',
        colorPalette: 'emerald-gold',
        illustrationPrompt: 'Robot Boti dengan lengan magnet ceria memilah kaleng di padang rumput bersama burung-burung',
      },
      {
        pageNumber: 4,
        sceneTitle: 'Tantangan Batang Pohon Raksasa',
        narrativeText: 'Tiba-tiba, sebuah batang pohon jati tua yang tumbang menimpa bendungan batu kecil. Baterai Boti mulai berkedip kuning tanda tenaganya menipis. Alih-alih panik, Kancil mencari sebatang kayu kokoh untuk dijadikan tuas pengungkit, seperti rahasia fisika sederhana yang selalu ia ingat.',
        englishTranslation: 'Suddenly, an old fallen teak log blocked the stone dam. Boti’s battery flashed yellow as power ran low. Instead of panicking, clever Mousedeer found a sturdy lever branch to lift the log.',
        dialogue: '"Kekuatan fisik ada batasnya, tetapi akal dan gotong royong tak pernah kehabisan tenaga!" kata Kancil.',
        interactiveQuestion: 'Pernahkah kamu menghadapi masalah sulit dan berhasil menyelesaikannya dengan akal cerdik?',
        activityPrompt: 'Tarik napas panjang dan dorong kedua tanganmu ke depan seakan mengangkat batang kayu besar!',
        sceneSetting: 'enchanted-forest',
        colorPalette: 'earthy-warm',
        illustrationPrompt: 'Kancil menggunakan tuas kayu cerdik dibantu Boti untuk menggeser batang kayu besar',
      },
      {
        pageNumber: 5,
        sceneTitle: 'Air Kembali Mengalir Riang',
        narrativeText: '"Satu... dua... tiga... angkat!" Dengan dorongan tenaga terakhir Boti dan tuas Kancil, batang kayu bergeser! Gemercik air danau langsung meluncur deras menyejukkan dasar hutan. Ikan nila melompat gembira ke udara, memantulkan pelangi mini di bawah sinar matahari sore.',
        englishTranslation: '"One... two... three... lift!" With one final push, the log shifted! Fresh lake water rushed joyfully through the stream, and fish leaped making miniature rainbows in the sunlight.',
        dialogue: '"Lihat Boti, airnya jernih kembali seperti cermin langit!" sorak Kancil gembira.',
        interactiveQuestion: 'Benda apa saja yang dapat memantulkan pelangi saat terkena cahaya matahari?',
        activityPrompt: 'Tepuk tangan tiga kali untuk merayakan keberhasilan Kancil dan Boti!',
        sceneSetting: 'mountain-river',
        colorPalette: 'azure-cyan',
        illustrationPrompt: 'Sungai mengalir deras berkilauan dengan cipratan pelangi dan ikan-ikan melompat riang',
      },
      {
        pageNumber: 6,
        sceneTitle: 'Persahabatan Abadi di Bawah Naungan Bintang',
        narrativeText: 'Malam pun tiba. Hewan-hewan hutan berkumpul memberikan buah kelapa manis untuk mengisi sel surya Boti. Di bawah kubah bintang yang berkelip, Boti memutuskan untuk menetap menjadi penjaga kebersihan hutan. Kancil dan Boti duduk bersandar di bawah pohon beringin tua, bersyukur atas berkah persahabatan sejati.',
        englishTranslation: 'Night arrived. Forest creatures gathered offering sweet coconut water to power Boti’s solar cells. Under the starry dome, Boti decided to stay as the forest guardian. They rested peacefully under the old banyan tree.',
        dialogue: '"Hati yang peduli adalah baterai terbaik yang tidak akan pernah padam," bisik Boti pelan.',
        interactiveQuestion: 'Kebaikan apa yang ingin kamu lakukan untuk alam di sekitarmu esok hari?',
        activityPrompt: 'Tutup matamu sejenak dan bayangkan kamu sedang memeluk pohon yang rindang.',
        sceneSetting: 'starry-sky',
        colorPalette: 'twilight-purple',
        illustrationPrompt: 'Kancil dan robot Boti duduk damai di bawah pohon beringin di bawah langit malam berbintang ungu keemasan',
      },
    ],
  },
  {
    id: 'bintang-kecil-samudra',
    title: 'Bintang Kecil yang Ingin Menyelam Samudra',
    tagline: 'Kisah tentang keberanian mengejar mimpi yang dianggap mustahil.',
    moralLesson: 'Setiap impian layak diperjuangkan, dan dunia akan membuka pintunya bagi hati yang tulus dan berani bertanya.',
    readingTimeMinutes: 4,
    targetAgeGroup: '4 - 7 Tahun',
    genre: 'Dongeng Fantasi Malam',
    artStyle: 'Pastel Anime Berkilau',
    characters: [
      { name: 'Twili', role: 'Bintang Emas Cilik', traits: 'Penuh rasa ingin tahu, bersinar kuning lembut', emoji: '⭐' },
      { name: 'Koralia', role: 'Penyu Laut Bijak', traits: 'Tempurung berlumut antik, penyayang dan sabar', emoji: '🐢' },
      { name: 'Gimi', role: 'Ikan Badut Ceria', traits: 'Lincah, jenaka, suka menari di antara anemon', emoji: '🐠' },
    ],
    cover: {
      visualDescription: 'Bintang kecil bercahaya meluncur lembut menyentuh permukaan ombak laut biru malam yang tenang.',
      sceneSetting: 'starry-sky',
      colorPalette: 'twilight-purple',
    },
    createdAt: '2026-10-01',
    pages: [
      {
        pageNumber: 1,
        sceneTitle: 'Pandangan dari Puncak Langit',
        narrativeText: 'Tinggi di angkasa, Twili adalah bintang kecil yang paling sering melongok ke bawah. Kakak-kakak bintangnya suka bercerita tentang awan, namun mata Twili selalu terpikat oleh kilau biru gelap nan luas di bumi: samudra samudra luas yang misterius.',
        englishTranslation: 'High in the sky, Twili was the smallest star who loved peering downward. While other stars talked about clouds, Twili was enchanted by the vast deep blue ocean on earth.',
        dialogue: '"Aku ingin tahu, apakah ikan-ikan di bawah sana juga bercahaya seperti kita di langit?" bisik Twili.',
        interactiveQuestion: 'Pernahkah kamu memandang langit malam dan memikirkan rahasia apa yang ada di sana?',
        activityPrompt: 'Kedipkan matamu pelan-pelan seperti bintang yang berkedip di angkasa!',
        sceneSetting: 'starry-sky',
        colorPalette: 'twilight-purple',
        illustrationPrompt: 'Bintang kecil tersenyum di angkasa biru indigo menatap ke bawah ke arah samudra berombak perak',
      },
      {
        pageNumber: 2,
        sceneTitle: 'Meluncur di Atas Sayap Angin Malam',
        narrativeText: 'Dengan izin dari Nenek Bulan, Twili mengubah cahayanya menjadi gelembung pelindung lembut. Ia meluncur turun seperti kembang api tenang, melintasi kabut awan putih, hingga "Plup!" mendarat dengan lembut di punggung Koralia, si penyu laut tua yang sedang mengapung santai.',
        englishTranslation: 'With Grandmother Moon’s gentle nod, Twili wrapped his glow in a soft protective bubble. He glided down like a quiet sparkler until "Plup!" he landed safely on wise old turtle Koralia’s shell.',
        dialogue: '"Wah, wah! Seumur hidupku mengarungi tujuh lautan, baru kali ini ada bintang mampir di tempurungku!" kata Koralia tertawa ramah.',
        interactiveQuestion: 'Hewan laut apa saja yang kamu ketahui selain penyu?',
        activityPrompt: 'Kembangkan kedua tanganmu dan ayunkan pelan seperti penyu berenang di air!',
        sceneSetting: 'cloud-kingdom',
        colorPalette: 'azure-cyan',
        illustrationPrompt: 'Bintang kecil dalam gelembung cahaya mendarat di atas tempurung penyu laut yang ramah',
      },
      {
        pageNumber: 3,
        sceneTitle: 'Taman Karang Neon yang Menyala',
        narrativeText: 'Koralia membawa Twili menyelam perlahan ke kedalaman terumbu karang. Twili terkesima! Di sana tidak gelap sama sekali. Karang-karang menyala merah muda, ungu, dan zamrud. Ikan badut bernama Gimi menyapa sambil berputar-putar di dalam anemon yang bergoyang lembut seperti tarian sutra.',
        englishTranslation: 'Koralia gently carried Twili down into the coral reef. It wasn’t dark at all! Corals glowed pink, violet, and emerald. Gimi the clownfish twirled happily among swaying sea anemones.',
        dialogue: '"Selamat datang di langit bawah air kami, Bintang Cilik!" sapa Gimi dengan putaran anggun.',
        interactiveQuestion: 'Warna apa saja yang menurutmu paling indah di dalam laut?',
        activityPrompt: 'Tirukan gerakan ikan berenang dengan menyatukan telapak tanganmu dan meliuk-liuk!',
        sceneSetting: 'underwater-coral',
        colorPalette: 'azure-cyan',
        illustrationPrompt: 'Pemandangan bawah laut menakjubkan dengan karang neon bercahaya dan ikan-ikan warna-warni',
      },
      {
        pageNumber: 4,
        sceneTitle: 'Menemukan Bintang Laut Kembar',
        narrativeText: 'Di dasar pasir putih yang bersih, Twili melihat makhluk cantik bertangan lima yang berbaring santai. "Apakah kamu bintang yang jatuh dari langit sepertiku?" tanya Twili heran. Makhluk itu tersenyum manis, "Bukan, aku Stella si Bintang Laut! Langit punya bintang di atas, dan bumi punya bintang di dasar samudra."',
        englishTranslation: 'On clean white sand, Twili saw a five-armed creature resting peacefully. "Are you a star fallen from the sky like me?" Twili asked. "No, I am Stella the Starfish! Sky has stars above, and sea has stars below."',
        dialogue: '"Kita berbeda tempat tinggal, namun kita sama-sama memancarkan keindahan," sahut Stella gembira.',
        interactiveQuestion: 'Mengapa perbedaan membuat dunia kita terasa begitu kaya dan menarik?',
        activityPrompt: 'Rentangkan kelima jarimu selebar-lebarnya seperti bentuk bintang laut!',
        sceneSetting: 'underwater-coral',
        colorPalette: 'candy-pink',
        illustrationPrompt: 'Twili si bintang langit berbincang akrab dengan bintang laut di atas pasir putih bersih',
      },
      {
        pageNumber: 5,
        sceneTitle: 'Dua Dunia yang Saling Menyinari',
        narrativeText: 'Ketika fajar hampir menyingsing, Koralia membawa Twili kembali ke permukaan laut. Angin pagi yang sejuk meniup Twili naik kembali ke singgasana birunya di langit. Sejak hari itu, setiap kali langit malam tiba, Twili berkedip ke arah laut, dan bintang-bintang laut di karang membalas dengan kilau air yang menyejukkan hati.',
        englishTranslation: 'As dawn approached, Koralia carried Twili back to the surface. Gentle morning breeze lifted Twili back to the blue sky. From that day on, Twili twinkled at the sea, and starfish glowed back in harmony.',
        dialogue: '"Mimpi tidak pernah terlalu jauh jika kita melangkah dengan ketulusan hati," bisik Twili bahagia.',
        interactiveQuestion: 'Mimpi apa yang paling ingin kamu wujudkan suatu hari nanti?',
        activityPrompt: 'Kirimkan senyuman terlebarmu kepada seseorang di sampingmu!',
        sceneSetting: 'starry-sky',
        colorPalette: 'twilight-purple',
        illustrationPrompt: 'Twili kembali melayang ke langit sambil melambaikan tangan kepada sahabat lautnya',
      },
    ],
  },
  {
    id: 'kuas-ajaib-seno',
    title: 'Kuas Ajaib Seno dan Pelangi yang Hilang',
    tagline: 'Setiap goresan warna membawa kebahagiaan bagi mereka yang membutuhkan.',
    moralLesson: 'Bakat dan kemampuan terbesar kita adalah yang dipergunakan untuk menghibur dan meringankan beban orang lain.',
    readingTimeMinutes: 5,
    targetAgeGroup: '6 - 9 Tahun',
    genre: 'Dongeng Petualangan & Budi Pekerti',
    artStyle: 'Gambar Pensil Warna & Cat Air',
    characters: [
      { name: 'Seno', role: 'Anak Pelukis', traits: 'Berhati lembut, imajinatif, selalu membawa buku sketsa', emoji: '🎨' },
      { name: 'Kakek Barata', role: 'Penjaga Toko Antik', traits: 'Rambut putih keperakan, bertutur kata bijaksana', emoji: '👴' },
      { name: 'Burung Cendrawasih', role: 'Utusan Pelangi', traits: 'Bulu semarak tujuh warna, terbang secepat kilat', emoji: '🦜' },
    ],
    cover: {
      visualDescription: 'Seorang anak memegang kuas kayu berujung emas yang meninggalkan jejak warna-warni pelangi di udara.',
      sceneSetting: 'village-morning',
      colorPalette: 'sunset-amber',
    },
    createdAt: '2026-10-01',
    pages: [
      {
        pageNumber: 1,
        sceneTitle: 'Hadiah dari Toko Tua di Sudut Desa',
        narrativeText: 'Di Desa Sukawarna, Seno dikenal sebagai anak yang paling suka menggambar bunga dan kupu-kupu. Pada hari ulang tahunnya, Kakek Barata memberinya sebuah kuas kayu tua dengan bulu halus keemasan. "Kuas ini hanya bekerja jika digerakkan oleh niat tulus untuk membahagiakan orang lain," pesan Kakek dengan senyum hangat.',
        englishTranslation: 'In Sukawarna village, Seno was known for his love of drawing flowers and butterflies. For his birthday, grandfather Barata gave him an old golden brush that only worked when moved by pure kindness.',
        dialogue: '"Peganglah dengan hatimu, bukan hanya dengan jemarimu," ujar Kakek Barata perlahan.',
        interactiveQuestion: 'Pernahkah kamu menerima hadiah yang sangat berharga dan berkesan bagimu?',
        activityPrompt: 'Gerakkan telunjukmu di udara seakan sedang melukis bentuk hati besar!',
        sceneSetting: 'magical-library',
        colorPalette: 'earthy-warm',
        illustrationPrompt: 'Kakek tua berjanggut putih memberikan kuas kayu berujung emas kepada anak laki-laki dengan mata berbinar',
      },
      {
        pageNumber: 2,
        sceneTitle: 'Desa yang Kehilangan Warnanya',
        narrativeText: 'Suatu sore usai hujan lebat, kabut kelabu aneh menyelimuti desa. Pelangi yang biasanya membentang megah di atas bukit tidak kunjung muncul. Rumah-rumah penduduk, sawah, dan taman bunga mulai memudar menjadi abu-abu kusam. Penduduk desa menjadi murung dan kehilangan semangat.',
        englishTranslation: 'One afternoon after heavy rain, strange gray mist wrapped the village. The great rainbow never appeared, and houses and flowers faded into dull gray. The villagers grew sorrowful.',
        dialogue: '"Ke mana perginya warna-warni indah desa kita?" keluh Ibu Seno dengan cemas.',
        interactiveQuestion: 'Bagaimana perasaanmu ketika melihat hari mendung dan hujan terus-menerus?',
        activityPrompt: 'Tirukan bunyi rintik hujan pelan: Tik... tik... tik... pada mejamu!',
        sceneSetting: 'village-morning',
        colorPalette: 'earthy-warm',
        illustrationPrompt: 'Desa berbukit yang murung dengan kabut abu-abu dan atap rumah yang kehilangan warnanya',
      },
      {
        pageNumber: 3,
        sceneTitle: 'Goresan Emas Pertama di Udara',
        narrativeText: 'Seno tidak tahan melihat tetangganya bersedih. Ia mengambil kuas ajaibnya dan mencelupkannya ke dalam tetesan embun jernih. Begitu kuas itu menyentuh udara, keluarlah pita cahaya merah merekah yang harum seperti mawar! Seno melompat dan melukis matahari cerah di atas atap rumah Nenek Aminah.',
        englishTranslation: 'Seno could not bear to see his neighbors sad. Dipping the magic brush into fresh dew, he touched the air and out flowed ribbon of scarlet light smelling of roses, bringing warmth back to the rooftops.',
        dialogue: '"Lihat! Bungaku mekar kembali!" seru Nenek Aminah dengan air mata bahagia.',
        interactiveQuestion: 'Jika kamu bisa memilih satu warna favorit untuk mewarnai duniamu, warna apa yang kamu pilih?',
        activityPrompt: 'Ucapkan warna favoritmu dengan suara paling ceria!',
        sceneSetting: 'village-morning',
        colorPalette: 'sunset-amber',
        illustrationPrompt: 'Seno mengayunkan kuas ajaib di udara, memancarkan pita warna merah dan emas yang menghidupkan bunga',
      },
      {
        pageNumber: 4,
        sceneTitle: 'Melukis Jembatan Pelangi Bersama',
        narrativeText: 'Melihat keajaiban itu, anak-anak desa berlari mendekat. Seno tidak menyimpan kuas itu untuk dirinya sendiri; ia membimbing tangan teman-temannya untuk bersama-sama melukis warna jingga, kuning, hijau, dan nila di langit. Kerja sama mereka membentuk lengkungan pelangi raksasa yang menyapu kabut kelabu hingga musnah!',
        englishTranslation: 'Seeing the magic, village children gathered. Seno did not keep the brush to himself; he guided their hands to paint orange, yellow, green, and indigo across the sky, creating a giant rainbow that chased the gray mist away!',
        dialogue: '"Ketika kita melukis bersama, warna pelangi menjadi seribu kali lebih berkilau!" teriak kawan-kawan Seno.',
        interactiveQuestion: 'Mengapa berbagi kebahagiaan dengan orang lain terasa jauh lebih nikmat daripada menikmatinya sendiri?',
        activityPrompt: 'Sebutkan 7 warna pelangi secara berurutan: Me-Ji-Ku-Hi-Bi-Ni-U!',
        sceneSetting: 'cloud-kingdom',
        colorPalette: 'candy-pink',
        illustrationPrompt: 'Anak-anak desa berpegangan tangan menatap pelangi raksasa tujuh warna yang membentang di angkasa',
      },
    ],
  },
  {
    id: 'naga-cilik-takut-gelap',
    title: 'Naga Cilik yang Takut Gelap',
    tagline: 'Bahkan makhluk paling perkasa pun memiliki hal yang mereka takuti.',
    moralLesson: 'Rasa takut adalah hal yang wajar; keberanian bukan berarti tidak takut sama sekali, melainkan berani melangkah walau hati berdebar.',
    readingTimeMinutes: 4,
    targetAgeGroup: '3 - 6 Tahun',
    genre: 'Dongeng Komedi Hangat',
    artStyle: 'Whimsical 3D Clay',
    characters: [
      { name: 'Gogo', role: 'Naga Cilik Hijau', traits: 'Sayap mini, pipi gembul, takut bayangan di malam hari', emoji: '🐲' },
      { name: 'Piko', role: 'Kunang-kunang Sahabat', traits: 'Buntut bercahaya hijau toska, periang dan setia', emoji: '🪲' },
      { name: 'Ibu Naga', role: 'Induk Naga Penyayang', traits: 'Nafas hangat, pelukan selembut selimut awan', emoji: '🐉' },
    ],
    cover: {
      visualDescription: 'Naga hijau imut berselimut daun besar sedang menatap kunang-kunang kecil yang menyala di dekat hidungnya.',
      sceneSetting: 'cozy-bedroom',
      colorPalette: 'emerald-gold',
    },
    createdAt: '2026-10-01',
    pages: [
      {
        pageNumber: 1,
        sceneTitle: 'Gua Batu yang Nyaman',
        narrativeText: 'Di Puncak Gunung Gemawan, tinggallah Gogo, seekor naga cilik bersisik hijau zamrud yang sangat menggemaskan. Gogo bisa menyemburkan gelembung api sebesar biji jagung untuk memanggang marshmallow. Namun setiap kali matahari terbenam dan lampu gua dimatikan, Gogo langsung bersembunyi di balik buntutnya!',
        englishTranslation: 'On Cloud Mountain lived Gogo, an adorable emerald dragon. Gogo could blow tiny popcorn flames for marshmallows. But when the sun set and cave lamps went off, Gogo hid behind his own tail!',
        dialogue: '"Ibuuu... bayangan batu itu tampak seperti monster bertanduk sepuluh!" rengek Gogo takut.',
        interactiveQuestion: 'Apakah kamu pernah merasa takut pada bayangan atau ruangan gelap?',
        activityPrompt: 'Tarik selimut bayanganmu ke atas dagu dan pejamkan mata rapat-rapat!',
        sceneSetting: 'cozy-bedroom',
        colorPalette: 'earthy-warm',
        illustrationPrompt: 'Naga kecil bersisik hijau bulat meringkuk ketakutan di atas tumpukan jerami dalam gua batu yang hangat',
      },
      {
        pageNumber: 2,
        sceneTitle: 'Sahabat Bercahaya Bernama Piko',
        narrativeText: 'Malam itu, seekor kunang-kunang mungil bernama Piko terbang masuk ke dalam gua. Piko tidak takut pada Gogo. Sebaliknya, ia mendarat tepat di ujung hidung bulat naga itu. "Mengapa kamu gemetar, Sobat Perkasa?" tanya Piko sambil mengedipkan cahaya buntutnya yang lembut seperti lentera.',
        englishTranslation: 'That night, a tiny firefly named Piko fluttered in. Piko was not scared of Gogo. Instead, he landed right on the dragon’s snout. "Why are you shaking, mighty friend?" Piko asked gently.',
        dialogue: '"Gelap itu menakutkan, Piko... Aku tidak bisa melihat apa yang ada di depanku," bisik Gogo malu.',
        interactiveQuestion: 'Benda apa yang biasanya menemanimu saat tidur agar merasa aman?',
        activityPrompt: 'Buatlah suara bisikan pelan: "Ssshhh... jangan takut, ada teman."',
        sceneSetting: 'cozy-bedroom',
        colorPalette: 'twilight-purple',
        illustrationPrompt: 'Kunang-kunang kecil bercahaya kuning neon bertengger di hidung naga cilik yang bermata besar',
      },
      {
        pageNumber: 3,
        sceneTitle: 'Permainan Bayangan Tangan yang Seru',
        narrativeText: 'Piko terbang ke depan nyala lilin kecil. Ia menggerakkan sayapnya sehingga tercipta bayangan kelinci melompat di dinding gua. Gogo tertawa terpingkal-pingkal! Gogo kemudian mencoba menggerakkan kedua cakarnya, membentuk bayangan burung merak yang mengepakkan bulunya.',
        englishTranslation: 'Piko flew before a tiny candle and cast a shadow bunny on the cave wall. Gogo giggled with joy! Gogo tried moving his claws, making shadow peacocks dancing on the rock.',
        dialogue: '"Wah! Ternyata bayangan bukan monster jahat, melainkan lukisan yang kita buat sendiri!" seru Gogo takjub.',
        interactiveQuestion: 'Bentuk hewan apa yang pernah kamu buat menggunakan bayangan tanganmu?',
        activityPrompt: 'Angkat kedua tanganmu dan buat bentuk kepakan burung merak!',
        sceneSetting: 'cozy-bedroom',
        colorPalette: 'sunset-amber',
        illustrationPrompt: 'Naga cilik dan kunang-kunang membuat bayangan kelinci dan burung lucu di dinding batu gua',
      },
      {
        pageNumber: 4,
        sceneTitle: 'Tidur Paling Nyenyak di Dunia',
        narrativeText: 'Piko berjanji akan selalu tidur di ranting depan gua Gogo setiap malam. Ibu Naga memeluk Gogo dengan sayap besarnya yang hangat. Malam itu, Gogo tidak lagi takut pada kegelapan. Ia tahu bahwa gelap hanyalah selimut hitam bertabur bintang yang disiapkan alam agar semua makhluk bisa beristirahat dengan damai.',
        englishTranslation: 'Piko promised to nest outside Gogo’s cave each night. Mother Dragon wrapped Gogo in her warm wings. That night, Gogo feared dark no longer, knowing darkness is just nature’s star-blanket for peaceful sleep.',
        dialogue: '"Selamat malam dunia. Besok kita bermain lagi!" bisik Gogo sebelum terlelap dengan senyuman manis.',
        interactiveQuestion: 'Doa atau ucapan apa yang selalu kamu sampaikan sebelum tidur di malam hari?',
        activityPrompt: 'Uapkan napas panjang: "Haaah..." lalu ucapkan: "Selamat tidur, mimpi indah!"',
        sceneSetting: 'cozy-bedroom',
        colorPalette: 'twilight-purple',
        illustrationPrompt: 'Naga cilik tertidur lelap memeluk boneka batu di samping ibunya dengan kunang-kunang menjaga di dekat jendela',
      },
    ],
  },
];
